%% assign lobe index to ROI of the Desikan-FS-86 atlas

% copied from R
ROIlobe86 = struct();
ROIlobe86.Frontal = {'Superiorfrontal' ...
    , 'Rostralmiddlefrontal', 'Caudalmiddlefrontal'...
    , 'Parsopercularis', 'Parstriangularis', 'Parsorbitalis' ...
    , 'Lateralorbitofrontal', 'Medialorbitofrontal' ...
    , 'Precentral', 'Paracentral', 'Frontalpole'};
ROIlobe86.Parietal = {'Superiorparietal', 'Inferiorparietal' ...
    , 'Supramarginal', 'Postcentral', 'Precuneus'};
ROIlobe86.Temporal = {'Superiortemporal', 'Middletemporal', 'Inferiortemporal' ...
    , 'Bankssts', 'Fusiform', 'Transversetemporal' ...
    , 'Temporalpole'};
ROIlobe86.Occipital = {'Lateraloccipital', 'Lingual' ...
    , 'Cuneus', 'Pericalcarine'};
ROIlobe86.Limbic = {'Rostralanteriorcingulate' ...
    , 'Caudalanteriorcingulate', 'Posteriorcingulate', 'Isthmuscingulate' ...
    , 'Hippocampus', 'Parahippocampal', 'Amygdala', 'Insula', 'Entorhinal'};
ROIlobe86.Subcortical = {'Accumbens_area', 'Caudate', 'Hypothalamus' ...
    , 'Cerebellum_Cortex' ...
    , 'Pallidum', 'Putamen', 'Thalamus_Proper'};


ROIlobe116.Frontal = {'Precentral', ...
    'Frontal_Sup', 'Frontal_Sup_Orb', 'Frontal_Sup_Medial', ...
    'Frontal_Mid', '10=Frontal_Mid_Orb_R', '9=Frontal_Mid_Orb_L', '26=Frontal_Mid_Orb_R', '25=Frontal_Mid_Orb_L', ...
    'Frontal_Inf_Oper', 'Frontal_Inf_Tri', 'Frontal_Inf_Orb', 'Rolandic_Oper', ...
    'Supp_Motor_Area', 'Olfactory', 'Rectus'};
ROIlobe116.Parietal = {'Postcentral', ...
    'Parietal_Sup', 'Parietal_Inf', ...
    'SupraMarginal', 'Angular', ...
    'Precuneus', 'Paracentral_Lobule'};
ROIlobe116.Temporal = {'Fusiform', 'Heschl', 'Temporal_Sup', 'Temporal_Inf', ...
    'Temporal_Pole_Sup', 'Temporal_Mid', 'Temporal_Pole_Mid'};
ROIlobe116.Occipital = {'Calcarine', 'Cuneus', 'Lingual', ...
    'Occipital_Sup', 'Occipital_Mid', 'Occipital_Inf', ...
    'Cerebelum_Crus1', 'Cerebelum_Crus2', ...
    'Cerebelum_3', 'Cerebelum_4_5', ...
    'Cerebelum_6', 'Cerebelum_7b', ...
    'Cerebelum_8', 'Cerebelum_9', ...
    'Cerebelum_10', ...
    'Vermis_1_2', 'Vermis_3', ...
    'Vermis_4_5', 'Vermis_6', ...
    'Vermis_7', 'Vermis_8', ...
    'Vermis_9', 'Vermis_10'};
ROIlobe116.Limbic = {'Cingulum_Ant', 'Cingulum_Mid', 'Cingulum_Post', 'Insula', 'ParaHippocampal', 'Hippocampus','Amygdala'};
ROIlobe116.Subcortical = {'Caudate', 'Putamen', 'Pallidum', 'Thalamus'};

%%
if (atsz == 86)
    ROIlobe = ROIlobe86;
elseif (atsz == 116)
    ROIlobe = ROIlobe116;
end


ff = fields(ROIlobe);
lobes = nan(size(ZonesName,1),1);
for idx = 1:length(ff)
    f = ff(idx);
    f = f{1};
    for ROI = ROIlobe.(f)
        I = find(cellfun(@(s)(~isempty(strfind(s,ROI{1}))), cellstr(ZonesName)));
        lobes(I) = idx;
    end
end
